title: 조형욱 Cho Hyung-wook # name of the site
author: fd7gu8 # name of site's author
email: x6k53e8zr@mozmail.com # email of site's author
url: https://fd7gu8.github.io # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  공간과 이동에 대한 데이터 기반의 해석 

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
goat_counter: "fd7gu8" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light" # "light", "dark" or "auto"
  back_home_text: "home" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page
  lowercase_titles: true # show titles in lowercase in lists

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  # - jektex

jektex:
  cache_dir: ".jektex-cache"
  ignore: ["*.xml"]
  silent: false
  macros:
    - ["\\Q", "\\mathbb{Q}"]
    - ["\\C", "\\mathbb{C}"]
    
# 2025-03-29에 추가한 코드 강조 설정
# 파이썬 코드 등에 문법 강조 색상을 적용하기 위한 설정입니다.
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
